### ISSUE TITLE
Looking forward to the open source of the dataset

### ISSUE THREAD

**Issue by wmpscc** [mqp2259/EdmCrack600#1]
I'm honored to read your paper entitled "A Cost Effective Solution for Road Crack Inspection using Cameras and Deep Neural Networks". Thank you very much for your related research, I have been doing similar work recently. I think the dataset produced by your team is very close to the industrial scene. I also want to test on such a dataset. Can you share it?
Thanks again.

**Comment by mqp2259** [comment]
Sorry for the delay. It is now released!
